version: "3"

services:

  ehr-sharing:
    image: docker.pkg.github.com/yylonly/medshare/index-center
    ports:
      - 8081:8080
    networks:
      - medshare-net
    depends_on:
      - gov-auth
      - index-center-db
      - gov-shared
    deploy:
      placement:
        constraints: [node.role == manager]
  
  index-center-db:
    image: docker.pkg.github.com/yylonly/medshare/index-center-db
    networks:
      - medshare-net
  
  gov-auth:
    image: docker.pkg.github.com/yylonly/medshare/gov-auth
    networks:
      - medshare-net
    ports:
      - 8080:8080
    depends_on:
      - gov-auth-db 
    deploy:
      placement:
        constraints: [node.role == manager]

  gov-auth-db:
    image: docker.pkg.github.com/yylonly/medshare/gov-auth-db
    networks:
      - medshare-net

  gov-shared:
    image: docker.pkg.github.com/yylonly/medshare/gov-shared
    networks:
      - medshare-net

networks:
  medshare-net:
